name: .NET CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      working-directory: ./TestTask
      run: dotnet restore TestTask.sln

    - name: Build
      working-directory: ./TestTask
      run: dotnet build TestTask.sln --no-restore --configuration Release

    - name: Run tests
      working-directory: ./TestTask
      run: dotnet test TestTask.sln --no-build --configuration Release --verbosity normal
